var _adpro=_adpro||{};if(_adpro.init)_adpro.init();else(function(){function v(d,a){var c=h.createElement(d),e;for(e in a)if(e===L)c[L]=a[e];else if(e===q)c[q]=a[e];else if(e===C)c.style.cssText=a[e];else if(e===X){var b=a[e],f=c;c[X]=c.onreadystatechange=function(){f.readyState&&"loaded"!==f.readyState&&"complete"!==f.readyState||b()}}else e===Y?c[Y]=a[e]:e===M?c[M]=a[e]:c.setAttribute(e,a[e]);return c}function Z(d,a,c,e){var b;b=""+(m+":"+a+";"+r+":"+d+";display:block;box-sizing: border-box;"+N);e&&(e===s?b+=s+":0;":e===O?b+=O+":0;":(a=a.match(/(\d+)([\w+%]*)/),
b+=s+":50%;margin-left:-"+a[1]/2+(a[2]+=";")));c&&(c===p?b+=P+";"+p+":0;":c===n?b+=P+";"+n+":0;":(d=d.match(/(\d+)([\w+%]*)/),b+=p+":50%;margin-top:-"+d[1]/2+(d[2]+=";")));if(c||e)b+="z-index:"+ga+";",b=5===h.documentMode?c===p?b+(t+";"+E+"(offsetParent.scrollTop);"):b+(t+";"+n+":auto;"+E+"(eval(("+k+"."+w+"."+F+"||"+k+".body."+F+")+("+k+"."+w+"."+G+"||"+k+".body."+G+")-"+$+"-("+aa+"(this.currentStyle.marginTop,10)||0)));"):8>Q?c===p?b+("_"+t+";_"+E+"(offsetParent.scrollTop);"):b+("_"+t+";_"+n+":auto;_"+
E+"(eval(("+k+"."+w+"."+F+"||"+k+".body."+F+")+("+k+"."+w+"."+G+"||"+k+".body."+G+")-"+$+"-("+aa+"(this.currentStyle.marginTop,10)||0)));"):b+(P+";");return v("div",{css:b})}function ba(d,a,c){c={scrolling:"no"};c[r]=ca;c[m]=ca;c.border=0;c.frameBorder=0;c[C]=m+":100%; "+r+":100%; background:transparent; overflow: hidden; frameBorder:0; "+N;c.src=R+"//"+H+"/ads2/"+f.upv+d+"?v="+da+"&slot="+a;c.allowTransparency="allowTransparency";return v("iframe",c)}function ha(d,a,c,e,b,f,h){var g={};g[q]=Q&&7>
Q?"<b>&times;</b>":"&#10006;";g[M]=function(){this[I].style.display="none";this[I][I].removeChild(this[I])};g[C]=(d===n?n+":0;":p+":0;")+(a===s?s+":0;":O+":0;")+'font-family:"Arial Unicode MS", "Lucida Sans Unicode";font-size:'+(c?c:"14px")+";color:"+f+";display:block;"+t+";"+N+";padding:"+(e?e:"0")+";_padding:"+(e?e:"0")+";margin:"+(b?b:"0")+";_margin:"+(b?b:"0")+";cursor:pointer;background: "+h+";line-height:100%;width:"+(c?c:"14px")+"; height:"+(c?c:"14px")+";text-align: center;";return v("div",
g)}function ia(d){var a="http://"+H+"/crawl/er.swf?initrc=_proCrawlerInit&"+Math.random(),c={};c[q]='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab" '+m+"=1 "+r+'=1 id=_proCrawlerCom name=_proCrawlerCom><param name=movie value="'+a+'"><param name=allowScriptAccess value=always><param name=quality value=low><embed src="'+a+'" allowscriptaccess=always quality=low '+m+"=1 "+r+'=1 name=_proCrawlerCom id=_proCrawlerCom type="application/x-shockwave-flash"></embed></object>';
c[C]=t+";"+n+":1px;"+s+":1px;"+m+":1px;"+r+":1px;overflow:hidden;";a=v("div",c);x[J](a,S);if("html"!==d.type){d="";var a=h[w][ja]("meta"),e;for(e in a)a[e].name&&-1<"description,keywords".indexOf(a[e].name[y]())&&(d+=a[e].getAttribute("content")[z]());a=[];for(e in h.links)h.links[e].href&&a[A]([h.links[e].href,h.links[e].innerText]);var b={};b[ka]=T;b[p]=K;b[la]=a;b[U]=ea;b[V]=h[V]?h[V][y]().replace(/\s{2,}/g," ").replace(/^\s+/,"").replace(/\s+$/,""):"";b.text=(d+" "+x[L])[y]().replace(/<\s*\/?\w+[^>]*>/g,
" ").replace(/[^0-9a-zA-Z\-\.\u4e00-\u9fa5]+/g," ")}window._proCrawlerInit=function(){var a=window._proCrawlerCom;a&&(a[B]&&(a.splice||a.item)&&(a=a[0].i8crawlPage?a[0]:a[1]),a.i8crawlPage&&a.i8crawlPage(R+"//"+H+"/crawl/er",b,window._proCrawlerDone?"_proCrawlerDone":""))}}var ma="string"!==typeof _adpro&&_adpro.length?_adpro:[],f=_adpro={slots:{},vars:""},da=2,H="m.adpro.cn",n="bottom",N="border:0;padding:0;margin:0;_padding:0;_margin:0;",C="css",G="clientHeight",k="document",w="documentElement",
ja="getElementsByTagName",r="height",ca="100%",q="innerHTML",L="innerText",J="insertBefore",s="left",B="length",M="onclick",Y="onkeyup",X="onload",I="parentNode",aa="parseInt",t="position:absolute",P="position:fixed",O="right",U="referrer",F="scrollTop",$="this.offsetHeight",V="title",y="toLowerCase",p="top",E="top:expression",z="toString",ka="URL",la="links",m="width",A="push",h=document,x=h.body,na=Math.random,u=encodeURIComponent,fa=0,R="https:"===h.location.protocol?"https:":"http:",S=x.firstChild,
ga=("To work with us, first talk to us: 6d6f632e646976616440746361746e6f63",2147483647)|0,K="",T=h.location+"",ea=h[U]+"",W=/msie ([\w.]+)/i.exec(window.navigator.userAgent),Q=W&&(W=+W[1])||!1,oa=/(_adpro_pub|_guanggao_pub)\s*=\s*"(\w+)";?\s*(_adpro_slot|_guanggao_slot)\s*=\s*"(\w+)"/;try{K=top.location+""}catch(pa){}f.medias=[];f.upv=function(){for(var d=32,a=((new Date).getTime()|0)[z](16);d--;)a+=(16*na()|0)[z](16);return a}();f[A]=function(d){if("string"!==typeof d&&d[B]){d="string"===typeof d[0]?
[d]:d;for(var a in d){f.vars+=",";for(var c in d[a])f.vars+=d[a][c]+","}}return f};f[A](ma);f.init=function(){f._init&&clearTimeout(f._init);f._init=setTimeout(function(){a:{for(var d=h.scripts,a=f.medias,c=((new Date).getTime()|0)[z](16),e=d[B],b=-1,D="",k="";++b<e;)if(!d[b].src&&d[b][q]&&d[b][q][B]){var g=d[b][q].match(oa);if(g&&g[4]){var l=g[2][y](),g=g[4][y]();f.slots[l]||(f.slots[l]={});if(!f.slots[l][g]){if(d[b].getAttribute("data-adpro"))break a;d[b].setAttribute("data-adpro",1);d[b].setAttribute("id",
l+"_"+g);f.slots[l][g]=1;D+=l+"_"+g+";";if(-1===a[z]().indexOf(l)){if(0<a.length)for(g=0;g<a.length;g++)(k+=a[g]+"_"+l+";")&&(k+=l+"_"+a[g]+";");a[A](l)}}}}if(0<D[B]){if(window._guanggao_vars&&0<window._guanggao_vars.length)for(var n in f.slots)for(var m in window._guanggao_vars)f[A]([n,_guanggao_vars[m][0],_guanggao_vars[m][1]]);d=f.vars;f.vars="";a={type:"text/javascript",async:!0,charset:"utf-8"};a.src=R+"//"+H+"/req2/?v="+da+"&upv="+f.upv+"&rid="+c+"&slots="+u(D)+"&vars="+u(d)+"&url="+u(T)+(T===
K?"":"&"+p+"="+u(K))+"&"+U+"="+u(ea)+"&overlap="+u(k)+"&count="+fa;c=v("script",a);x[J](c,S);fa++}}},250)};f.crawl=function(d){f._crawl||(f._crawl,ia(d))};f.show=function(d){for(var a in d){var c=d[a].type;if("fixed"===c){var c=d.rid,e=a,b=d[a],f=Z(b.height,b.width,b.v,b.h);f.appendChild(ha(b.closeV,b.closeH,b.closeFontSize,b.closePadding,b.closeMargin,b.closeColor,b.closeBackground));f.appendChild(ba(c,e,b));x[J](f,S)}else if("static"===c&&(e=d.rid,b=a,f=d[a],c=Z(f.height,f.width),c.appendChild(ba(e,
b,f)),e=h.getElementById(b)))e.parentNode[J](c,e.nextSibling||null)}};f.init()})();
//13.11.20